 <div class="container-fluid">
    <div class="row justify-content-center">
          <div class="col-12 col-sm-6 col-md-7 form-registro p-4">
          <h2 >Ingresar Proveedor</h2> <hr>
                <form action="" method="post" class="form-prov">
                    <input type="hidden" name="agregar" value="1">
                     <div class="card-body">
                        <div class="row"> 
                            <div class="col-md-6">
                                <label for="id_area">ID</label>
                                    <input type="text" class="form-control" id="p_id" name="p_id" placeholder="Automatic" disabled>
                            </div>
                            <div class="col-md-6"></div>
                            <div class="col-md-6 mt-3">
                                <label for="nom_prov">Nombre</label>
                                <input type="text" class="form-control" id="nom_prov" name="nom_prov" required autocomplete="off">
                            </div>
                            <div class="col-md-6 mt-3">
                                <label for="dir_prov">Dirección</label>
                                <input type="text" class="form-control" id="dir_prov" name="dir_prov" required autocomplete="off">
                            </div>
                            <div class="col-md-6 mt-3">
                                <label for="tel_prov">Telefono</label>
                                <input type="text" class="form-control" id="tel_prov" name="tel_prov" required autocomplete="off">
                            </div>
                            <div class="col-md-6 mt-3">
                                <label for="rep_prov">Representante</label>
                                <input type="text" class="form-control" id="rep_prov" name="rep_prov" required autocomplete="off">
                            </div>
                            
                        </div>
                      </div>
                      <div class="card-body text-center ">
                        <button type="submit" class="btn btn-info btn-block">Enviar</button>
                      </div>
                </form>
            </div>
        </div>
    </div>
</div>