<!--Contenido-->
<div class="container-fluid">
  <!-- Inicio Contenido -->

<?= $this->titulo ?>
      
  <div class="row">   
    <div class="col-md-9 col-xs-12 mt-4">
      <div class="card shadow mb-4">
          <div class="card-body">
            <div class="table-responsive">
              <table id="dataTable" class="table table-striped table-bordered " style="width:100%">
                <thead>
                <tr>
                    <td>ID</td>
                    <td>Proveedor</td>
                    <td>Dirección</td>
                    <td>Telefono</td>
                    <td>Representante</td>
                    <td>Acciones</td>
                </tr>
              </thead>
              <tbody>
                <?= $this->contenido ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-3 col-xs-12 mt-4">
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Ingresar Proveedor</h6>
      </div>
        <div class="card-body">
          <form action="" method="post" class="form-group">
            <input type="hidden" name="add" value="1">
              <div class="form-group">
                <label for="proveedor">Proveedor</label>
                  <input type="text" name="p_nom" id="p_nom" class="form-control">
                </div>
                <div class="form-group">
                <label for="direccion">Dirección</label>
                  <input type="text" name="p_dir" id="p_dir" class="form-control">
                </div>
                <div class="form-group">
                <label for="telefono">Telefono</label>
                  <input type="text" name="p_tel" id="p_tel" class="form-control">
                </div>
                <div class="form-group">
                <label for="representante">Representante</label>
                  <input type="text" name="p_rep" id="p_rep" class="form-control">
                </div>
                <div class="text-center">
                  <input type="submit" value="Agregar" class="btn btn-primary">
                </div>
            </form>
        </div>
      </div>

  
  </div>


</div>
<!-- /.container-fluid -->

</div>
<!-- fin del contenido -->


<div class="modal fade" id="Editar_prove" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form action="" method="POST">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Editar Información</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <input type="hidden" name="editar_prov" value="1">
            <div class="form-group">
              <label for="proveedor">Proveedor</label>
              <input type="text" name="p_nom" id="p_nom" class="form-control">
            </div>
            <div class="form-group">
                <label for="direccion">Dirección</label>
                  <input type="text" name="p_dir" id="p_dir" class="form-control">
                </div>
                <div class="form-group">
                <label for="telefono">Telefono</label>
                  <input type="text" name="p_tel" id="p_tel" class="form-control">
                </div>
                <div class="form-group">
                <label for="representante">Representante</label>
                  <input type="text" name="p_rep" id="p_rep" class="form-control">
                </div>
          </div>
          <div class="modal-footer">
            <input type="submit" value="Guardar Cambios" class="btn btn-primary">
            
          </div>
        </form>
      </div>
    </div>
  </div>
    