<div class="container-fluid">
  <div class="row justify-content-center ">
    <div class="col-12 col-sm-6 col-md-10 form-registro p-2">
      <div class="bd-highlight"><h2 class="p-3">Agregar Libro</h2> <hr></div>
        <form action="" method="POST" class="form-libro">
          <input type="hidden" name="agregar" value="1">
            <div class="card-body">
              <div class="row"> 
                <div class="col-md-4">
                  <label for="codigo">Código</label>
                  <input type="text" name="codigo" id="codigo" class="form-control" require autocomplete="off">
                </div>
                <div class="col-md-4">
                  <label for="titulo">Titulo</label>
                  <input type="text" name="titulo" id="titulo" class="form-control" require autocomplete="off">
                </div>
                <div class="col-md-4">
                  <label for="autor">Autor</label>
                  <input type="text" name="autor" id="autor" class="form-control" require>
                </div>
                <div class="col-md-5 mt-3">
                  <label for="editorial">Editorial</label>
                  <input type="text" name="editorial" id="editorial" class="form-control" require>
                </div>
                <div class="col-md-5 mt-3">
                  <label for="edicion">Edición</label>
                  <input type="text" name="edicion" id="edicion" class="form-control" require>
                </div>
                <div class="col-md-2 mt-3">
                  <label for="year">Año</label>
                  <input type="number" name="year" id="year" class="form-control" require>
                </div>
                <div class="col-md-4 mt-3">
                  <label for="categoria">Categoría</label>
                  <select name="categoria" id="categoria" class="form-control" require>
                  <?=$this->categoria?>
                  </select>
                </div>
                <div class="col-md-3 mt-3">
                  <label for="proveedor">Proveedor</label>
                  <select class="form-control" name="proveedor" id="proveedor">
                    <?= $this->proveedor?>
                  </select>
                </div>
                <div class="col-md-3 mt-3">
                  <label for="fingreso">Fecha Ingreso</label>
                  <input type="date" name="fingreso" id="fingreso" class="form-control" require>
                </div>
                <div class="col-md-2 mt-3">
                  <label for="cantidad">Cantidad</label>
                  <input type="number" name="cantidad" id="cantidad" class="form-control" require>
                </div>
            </div>
            <div class="card-body text-center mt-4">
              <button type="submit" class="btn btn-info btn-block" >Agregar</button>
            </div>
        </form>
    </div>
  </div>
</div>
<br>
<br>

</div>

<!-- /.container-fluid -->
</div>
<!-- fin del contenido -->
