<!--Contenido-->
<div class="container-fluid">
  <!-- Inicio Contenido -->
  <h1 class="h3 text-gray-800 text-center">Agregar Libro</h1>

  <div class="card shadow mb-4">
    <div class="card-body">
      <form action="" method="post" class="form-group">
        <input type="hidden" name="add" value="1">
          <div class="row">
          <div class="col-md-4">
              <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" name="l_nom" id="l_nom" class="form-control" require>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="autor">Autor</label>
                <input type="text" name="l_aut" id="l_aut" class="form-control" require>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="area">Area</label>
                <input type="text" name="l_ar" id="l_ar" class="form-control" require>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="edicion">Edición</label>
                <input type="text" name="l_edic" id="l_edic" class="form-control" require>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="editor">Editor</label>
                <input type="text" name="l_ed" id="l_ed" class="form-control" require>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="proveedor">Proveedor</label>
                <select class="form-control" name="l_prov" id="l_prov">
                  <?= $this->proveedores; ?>
                </select>
              </div>
            </div>
            <div class="col-md-2">
              <div class="form-group">
                <label for="npaginas"># Pagínas</label>
                <input type="number" name="l_np" id="l_np" class="form-control" require>
              </div>
            </div>
            <div class="col-md-2">
              <div class="form-group">
                <label for="fingreso">Fecha Ingreso</label>
                <input type="date" name="l_fi" id="l_fi" class="form-control" require>
              </div>
            </div>
            <div class="col-md-2">
              <div class="form-group">
                <label for="cantidad">Cantidad</label>
                <input type="number" name="l_cant" id="l_cant" class="form-control" require>
              </div>
            </div>
            <div class="col-md-2">
              <div class="form-group">
                <label for="precio">Costo</label>
                <input type="number" name="l_pre" id="l_pre" class="form-control" require>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label for="obse">Observaciones</label>
                <input type="text" name="l_obs" id="l_obs" class="form-control" >
              </div>
            </div>   
          </div>
          <div class="text-center ">
            <input type="submit" value="Agregar" class="btn btn-primary">
          </div>
      </form>
    </div>
  </div>
</div>



<!-- /.container-fluid -->
</div>
<!-- fin del contenido -->
