<body id="coloresme">
      <div class="container-fluid">
        <div class="row justify-content-center">
          <div class="col-12 col-sm-6 col-md-5 login-b">
            <h2 class="text-center">Biblioteca Hillcrest</h2> <hr>
              <form method="POST" class="user ">
                <div class="icon-login mb-3"><i class="fa fa-user-circle"></i></div>
                <h2 class="text-center text-info">Iniciar Sesión</h2>
                <input type="hidden" name="ingresar" value="1">
                
                  <div class="input-group mb-3">
                    <div class="input-group-append">
                        <div class="input-group-text">
                          <span class="fas fa-user"></span>
                        </div>
                      </div>
                    <input type="text" class="form-control"  name="usuario" id="usuario" placeholder="Ingresa el nombre de usuario" required> 
                    </div>
                    <div class="input-group mb-3">
                      <div class="input-group-append">
                        <div class="input-group-text">
                          <span class="fas fa-lock"></span>
                        </div>
                      </div>
                    <input type="password" class="form-control"  name="password" id="password" placeholder="Ingresa tu contraseña" required>
                    </div>
                    <?php if (isset($this->mensaje)) echo $this->mensaje; ?>
                    <div class="text-center">
                      <button type="submit" value="Login" class="btn btn-info">Acceder</button>
                    </div>
              </form>
          </div>
        </div>
      </div>

</body>

