
<div class="container-fluid">
    <div class="row justify-content-center">
          <div class="col-12 col-sm-6 col-md-7 form-registro p-4">
          <h2 >Insertar Área de Estudio</h2> <hr>
                <form action="" method="post" class="form-catg">
                    <input type="hidden" name="agregar" value="1">
                     <div class="card-body">
                        <div class="row"> 
                            <div class="col-md-6">
                                <label for="id_area">ID</label>
                                    <input type="text" class="form-control" id="id_area" name="id_area" placeholder="Automatic" disabled>
                            </div>
                            <div class="col-md-6">
                                <label for="area">Categoría</label>
                                <input type="text" class="form-control" id="area" name="area" required autocomplete="off">
                            </div>
                            <div class="col-md-12 mt-3">
                                <label for="descripcion">Descripción</label>
                                <input type="text" class="form-control" id="descripcion_area" name="descripcion_area" required autocomplete="off">
                            </div>
                        </div>
                      </div>
                      <div class="card-body text-center ">
                        <button type="submit" class="btn btn-info btn-block">Enviar</button>
                      </div>
                </form>
            </div>
        </div>
    </div>
</div>