<div class="container-fluid">
  <div class="card shadow mb-4">
    <div class="card-header ">
      <div class="d-flex bd-highlight mb-3">
        <div class="mr-auto p-2 bd-highlight"><h4>Lista de categorías registradas</h4></div>
        <div class="p-2 bd-highlight"><a href="<?= BASE_URL ?>areas/agregarareas" class="btn btn-dark">
        <span class="fa fa-plus mr-2"></span> Agregar Nueva</a></div>
      </div>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered table-hover tablaArea" id="dataTable" width="100%"> 
        <thead>
          <tr>
            <th class="text-center">#</th>
            <th class="text-center">Área</th>
            <th class="text-center">Descripción</th>
            <th class="text-center">Editar</th>
            <th class="text-center">Eliminar</th>
          </tr>
        </thead>
        <tbody>
          <?=$this->tabla ?>
        </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>
 


<div class="modal fade" id="editcat">
        <div class="modal-dialog ">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title font-weight-normal">Actualizar Categoria</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form id="formEditcta" method="post" class="form" >
                <input type="hidden" id="base" value="<?= BASE_URL ?>">
                <input type="hidden" name="editar" value="1">
                <div class="card-body">
                  <input type="hidden" class="form-control" id="id_area" name="id_area">
                  <div class="row form-group">
                    <div class="col-sm-3">
                      <label class="control-label" style="position:relative; top:7px;">Categoría:</label>
                    </div>
                    <div class="col-sm-9">
                     <input type="text" class="form-control" id="area" name="area">
                    </div>
                  </div>
                  <div class="row form-group">
                    <div class="col-sm-3">
                      <label class="control-label" style="position:relative; top:7px;">Descripción:</label>
                    </div>
                    <div class="col-sm-9">
                     <textarea type="text" class="form-control" id="descripcion_area" name="descripcion_area"  rows="3"></textarea>
                    </div>
                  </div>
                </div>
            </div>
            <div class="modal-footer text-center">
              <button type="submit" class="btn btn-info">Guardar Cambios</button>
            </div>
          </form>
          </div>
          <!-- /.modal-content -->
        </div>
      </div>